### ISSUE TITLE
Question: Sync JSON.parse is more memory efficient than streaming?

### ISSUE THREAD

**Issue by mykhailoklym94** [juanjoDiaz/streamparser-json#43]
Hi @juanjoDiaz, thanks for the library, so far great APIs and quite nice to use, however I have a slight problem. 

In short, I can describe it like this: streaming json file of 150MB via `streamparser-json` requires 1GB of RAM, while parsing via `JSON.parse` would require 500MB for processing the same file.

Please see a more detailed explanation below:

I have to process JSON files that are usually 150-400 MB. For this example, I am working with 150MB of JSON. 

For weird reasons JSONs that I have to work with have this structure:
```jsonc
{
    "TABLE": [
        {
            "OBJECT_1": {
                "OBJECT_1_KEY_1": "OBJECT_1_VALUE_1",
                "OBJECT_1_KEY_2": "OBJECT_1_VALUE_2"
                // ... more properties
            },
            "OBJECT_2": {
                "OBJECT_2_KEY_1": "OBJECT_2_VALUE_1",
                "OBJECT_2_KEY_2": "OBJECT_2_VALUE_2"
                // ... more properties
            }
            // ... more objects
        }
    ]
}
```
So, if we were to generalize this, my JSON would always contain TABLE property, in this TABLE property I want to always get the first object and inside this first object I want to stream all objects one by one (weird data structure but I have to deal with it).

So, I wrote a simple script that would provide me objects one by one and that works great - e.g. it produces data object by object.

```javascript
const fs = require('node:fs')
const { JSONParser } = require('@streamparser/json-node')

const main = async () => {
  const jsonStream = await fs.createReadStream('./tab_config.json');

  const parser = new JSONParser({ stringBufferSize: undefined, paths: ['$.TABLE.*.*'], keepStack: false });

  const pipeline = jsonStream.pipe(parser);

  pipeline.on('data', (object) => {
    // got OBJECT_1, OBJECT_2 ... etc.
  })
}

main();

```

However, when I inspect RAM usage – for processing 150MB file – this script will peak at memory usage at almost 1GB.
<img width="670" alt="image" src="https://github.com/juanjoDiaz/streamparser-json/assets/24704421/d105127d-5b8e-46ff-ad62-3876dea21ad1">

On the contrary, if I were to use simple JSON.parse and blow entire stuff into memory – amount of used RAM would go down to ~600MB
```javascript
const nonStreaming = async () => {
  const file = await fs.promises.readFile('./tab_config.json');
  const parsed = JSON.parse(file);

  console.log('parsed file')
}

nonStreaming();
```
<img width="707" alt="image" src="https://github.com/juanjoDiaz/streamparser-json/assets/24704421/3fa19b71-1856-48bf-af7a-f4a30f18e1a2">

So my questions are:

- Could you kindly explain why could it happen? I would be expecting `streamparser-json` to use way less memory and stream objects one by one.
- I assume the problem is somewhere on my side, could you point me to what can it be?

Once again, thanks a lot for the library I really hope I can use it.

**Comment by mykhailoklym94** [comment]
I realized that I do have some large strings in the JSON – I've tried setting `stringBufferSize: 0`, but that had no effect whatsoever. RAM usage is still around 1GB.

**Comment by mykhailoklym94** [comment]
Okay, I think I got it :) setting `stringBufferSize: 64 * 1024` solved it for me. I still don't fully understand what it does, but after applying this setting memory consumption went down significantly - and is now about 200MB, which is great 👏. 

<img width="671" alt="image" src="https://github.com/juanjoDiaz/streamparser-json/assets/24704421/cbd0ec9b-99b5-4697-99a8-0662f15e43e7">

P.S. I will try to understand how it works and maybe try to provide a PR with a better explanation for `README`, because for me, to be honest, it was not clear. Only after seeing your performance tests I came up with this value 😄

Once again many thanks for the library, looks great 🔥

**Comment by juanjoDiaz** [comment]
Hi @mykhailoklym94,

`JSON. parse` will always be faster and more efficient that any other type of parsing because it's written in C++ and optimized by the browser.

The sync API of streamparser-json will be slower because of this and take more memory because it parse data byte by byte, emits all the parsed tokens, keep objects in memory, etc... In JavaScript, you can't control the garbage collector (gc). So, memory will be consume by temporary objects until gc kicks in freeing space.

The async API of streamparser-json will be slower because of the overhead introduce by streaming the content (backpressure and all that). But it has the advantage of not flooding the memory.
Especially for streaming huge objects, I implemented `paths: ['<something>']`and `keepStack: false`. So, only relevant path are emitted and the root object is not kept in memory.

Going back to `stringBufferSize: 64 * 1024` and why is solves you memory issues.

When you stream data in node, data is stream in batches (the batch size is configured using the [highWatermark](https://nodejs.org/en/learn/modules/backpressuring-in-streams) property.
This means, that a long stream will be read as many smaller pieces.

When you use `stringBufferSize: 0`, every character is read as a string and concatenated to a string used as a buffer. This is fast but it's inefficient in terms of memory because in JavaScript strings are immutable i.e. every time you concatenate 2 strings you actually create a third string. So, if you parse a string of 100 character, you will have a few hundres of tiny strings in memory until the gc kicks in.
When using a bigger buffer, the characters are stored in a fixed-sized Arraybuffer and concatenated only once once the string is ready of the buffer is full. So, there is a lot less objects in memory and a lot less work for the gc.

Hope this clarifies things 🙂
